-- 기사 테이블
CREATE TABLE IF NOT EXISTS articles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  summary TEXT,
  category TEXT NOT NULL DEFAULT 'AI교육',
  author TEXT NOT NULL,
  tags TEXT[] DEFAULT '{}',
  published BOOLEAN DEFAULT false,
  image_url TEXT,
  views BIGINT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_articles_category ON articles(category);
CREATE INDEX IF NOT EXISTS idx_articles_published ON articles(published);
CREATE INDEX IF NOT EXISTS idx_articles_created_at ON articles(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_articles_views ON articles(views DESC);

-- 조회수 증가 함수
CREATE OR REPLACE FUNCTION increment_views(article_id BIGINT)
RETURNS void AS $$
BEGIN
  UPDATE articles
  SET views = views + 1
  WHERE id = article_id;
END;
$$ LANGUAGE plpgsql;

-- updated_at 자동 업데이트 트리거
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_articles_updated_at
  BEFORE UPDATE ON articles
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at();

-- 샘플 데이터
INSERT INTO articles (title, content, summary, category, author, tags, published) VALUES
(
  'AI 시대, 유치원 선생님이 알아야 할 5가지',
  '# AI 시대, 유치원 선생님이 알아야 할 5가지

생성형 AI가 유아 교육 현장에 가져온 변화는 이미 우리 곁에 와 있습니다. 이번 기사에서는 유치원 선생님이 알아야 할 핵심 내용을 정리했습니다.

## 1. ChatGPT 같은 AI 도구 활용법

교육 계획안 작성, 활동 아이디어 생성, 학부모 연락 초안 작성 등 다양하게 활용할 수 있습니다.

## 2. AI 윤리 교육의 중요성

어린이들에게 AI가 만든 결과물과 사람이 만든 결과물의 차이를 이해시키는 것이 중요합니다.

## 3. 개인정보 보호

아이들의 사진이나 정보를 AI에 입력할 때 주의가 필요합니다.

## 4. AI와 함께하는 창의적 활동

AI 그림 도구로 아이들의 상상력을 확장할 수 있습니다.

## 5. 지속적인 학습

AI 기술은 빠르게 발전하므로 선생님들도 계속 학습해야 합니다.',
  '생성형 AI가 유아 교육에 미치는 영향과 활용 방법을 5가지 핵심 포인트로 정리했습니다.',
  'AI교육',
  '김지현',
  ARRAY['AI', '유치원', '교육', 'ChatGPT'],
  true
),
(
  '교육부, 2025년 유치원 AI 교육 지원 확대',
  '# 교육부, 2025년 유치원 AI 교육 지원 확대

교육부가 2025년부터 전국 유치원을 대상으로 AI 교육 지원을 대폭 확대한다고 밝혔습니다.

## 주요 지원 내용

- **AI 교육 기자재 보급**: 1억 원 규모의 태블릿 및 AI 기자재 지원
- **교사 연수**: 연 2,000명 대상 AI 활용 연수
- **커리큘럼 개발**: 유아용 AI 교육 표준 커리큘럼 보급

## 기대 효과

교육부 관계자는 "이번 지원을 통해 유치원 교육 현장의 AI 활용도를 높이고, 디지털 전환에 따른 교육 격차를 줄이겠다"고 밝혔습니다.',
  '정부가 발표한 새로운 AI 교육 지원 정책의 핵심 내용을 정리했습니다.',
  '정책',
  '박민수',
  ARRAY['교육부', '정책', 'AI', '지원'],
  true
),
(
  '경기 유치원 "AI 활용해서 부모 신뢰 얻어요"',
  '# 경기 유치원 "AI 활용해서 부모 신뢰 얻어요"

경기도의 한 유치원이 AI를 활용해 학부모 소통을 혁신한 사례를 소개합니다.

## 사례 소개

**행복꿈이 유치원**(가명)은 작년부터 AI를 활용한 알림장 서비스를 도입했습니다.

### 활용 방법

- AI가 자동으로 아이들의 활동 내용을 정리
- 사진과 함께 자연스러운 문장 생성
- 개별 맞춤형 피드백 제공

### 결과

- 학부모 만족도 40% 상승
- 선생님의 행정 업무 시간 50% 감소
- 가정 연계 활동 참여율 증가

원장님은 "AI가 선생님의 업무를 대체하는 것이 아니라, 아이들에게 더 집중할 수 있게 도와준다"고 말했습니다.',
  '실제 현장에서 AI를 활용해 소통을 개선한 유치원 사례입니다.',
  '유치원',
  '이수진',
  ARRAY['유치원', '사례', 'AI', '소통'],
  true
),
(
  '우리 아이 AI 교육, 어디서부터 시작할까요?',
  '# 우리 아이 AI 교육, 어디서부터 시작할까요?

초보 학부모를 위한 AI 교육 시작 가이드입니다.

## 1단계: AI 체험하기

- AI 그림 도구로 함께 그려보기
- AI 이야기 만들기 게임
- AI 음악 감상

## 2단계: AI 이해하기

- AI는 어떻게 학습하는지 알기
- AI가 잘하는 것과 못 하는 것 구별하기
- AI 윤리 함께 이야기하기

## 3단계: 안전하게 활용하기

- 개인정보 입력하지 않기
- AI 결과를 비판적으로 보기
- 사람과 함께 사용하기

## 추천 자료

- 『어린이를 위한 AI 첫걸음』
- EBS AI 교육 동영상
- 국가평생교육진흥원 AI 교육',
  '초보 학부모를 위한 AI 교육 가이드입니다.',
  '학부모',
  '정유미',
  ARRAY['학부모', 'AI', '가이드', '교육'],
  true
),
(
  '[인터뷰] AI 교육 선구자 원장님의 이야기',
  '# [인터뷰] AI 교육 선구자 원장님의 이야기

경기도의 한 유치원에서 3년 전부터 AI 교육을 시작한 김OO 원장님을 만났습니다.

## 시작 계기

"처음에는 선생님들의 반응이 冷冷했습니다. 하지만 직접 체험해보니 생각이 바뀌더라고요."

## 도입 과정

1. **1기차**: 교사 연수부터 시작
2. **2기차**: 간단한 도구부터 활용
3. **3기차**: 전면 확대

## 현재 모습

- 매주 AI 활용 수업 진행
- 학부모 대상 AI 교육 워크숍
- 타 유치원 벤치마킹 방문

## 조언

"무조건 도입하기보다, 왜 필요한지부터 고민해보세요. 아이들을 위한 교육이 핵심입니다."',
  '경기의 한 유치원에서 시작된 AI 교육 혁신 이야기입니다.',
  '인터뷰',
  '편집부',
  ARRAY['인터뷰', '원장님', 'AI', '혁신'],
  true
),
(
  '프롬프트 공부의 정석, 전문가가 알려줘요',
  '# 프롬프트 공부의 정석, 전문가가 알려줘요

효율적인 AI 활용을 위한 프롬프트 작성법을 소개합니다.

## 좋은 프롬프트의 5가지 요소

### 1. 역할 부여
"당신은 유아 교육 전문가입니다"

### 2. 구체적 상황
"5세 아이들이 대상인"

### 3. 명확한 목표
"봄 활동 계획안을 작성해주세요"

### 4. 출력 형식
"표 형태로 정리해주세요"

### 5. 예시 제시
"이런 활동이 있어요: ..."

## 실전 예시

❌ "봄 활동 알려줘"
✅ "유아 교육 전문가로서, 5세 아이들을 위한 실내 봄 활동 5개를 제안해주세요. 각 활동은 목표, 준비물, 활동 과정으로 구성해주세요."

## 더 배우고 싶다면

- 스마택트 프롬프트 라이브러리
- Prompt Engineering Guide',
  '효율적인 AI 활용을 위한 프롬프트 작성법을 전문가가 알려드립니다.',
  'AI교육',
  '최현우',
  ARRAY['프롬프트', 'AI', 'ChatGPT', '활용'],
  true
);

-- 뉴스레터 구독자 테이블
CREATE TABLE IF NOT EXISTS subscribers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_subscribers_email ON subscribers(email);
CREATE INDEX IF NOT EXISTS idx_subscribers_active ON subscribers(active);
